spring:
  application:
    name: ms-cliente-persona

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_clientes}
    username: ${SPRING_DATASOURCE_USERNAME:banco_user}
    password: ${SPRING_DATASOURCE_PASSWORD:banco_pass_2024}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: America/Guayaquil
    open-in-view: false

  jackson:
    time-zone: America/Guayaquil
    serialization:
      write-dates-as-timestamps: false

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:banco}
    password: ${SPRING_RABBITMQ_PASSWORD:banco123}

server:
  port: ${SERVER_PORT:8081}

rabbitmq:
  exchange:
    name: banking.exchange
  queue:
    name: cliente.eventos.queue
  routing:
    key:
      cliente: cliente.eventos

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.banco.cliente: DEBUG
    org.springframework.amqp: INFO
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
